//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SESWeb.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"http://bilpip.bi.com:50000/XISOAPAdapter/MessageServlet?channel=:BS_BI_TARGET_WEBPORTAL_D:SOAPSender_CashVoucherFromWEBPORTAL&version=3.0&Sender.Service=SOAPSender_CashVoucherFromWEBPORTAL+&Interface=urn%3ATARGET%3AWEBPORTAL%3ACashVoucher%5ECashVoucherFromWEBPORTAL_Out")]
        public string ESS_wsvcSAPPIExpenseReimbursement_CashVoucherFromWEBPORTAL_OutService {
            get {
                return ((string)(this["ESS_wsvcSAPPIExpenseReimbursement_CashVoucherFromWEBPORTAL_OutService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://brakesindia.versionsystems.com/WebService/EmployeeBalance.asmx")]
        public string ESS_PFService_EmployeeBalance {
            get {
                return ((string)(this["ESS_PFService_EmployeeBalance"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"http://bilpip.bi.com:50000/XISOAPAdapter/MessageServlet?channel=:BS_BI_TARGET_WEBPORTAL_D:SOAPSender_CashVoucherFromWEBPORTAL&version=3.0&Sender.Service=SOAPSender_CashVoucherFromWEBPORTAL+&Interface=urn%3ATARGET%3AWEBPORTAL%3ACashVoucher%5ECashVoucherFromWEBPORTAL_Out")]
        public string SESWeb_wsvcSAPPIExpenseReimbursement_CashVoucherFromWEBPORTAL_OutService {
            get {
                return ((string)(this["SESWeb_wsvcSAPPIExpenseReimbursement_CashVoucherFromWEBPORTAL_OutService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://brakesindia.versionsystems.com/WebService/EmployeeBalance.asmx")]
        public string SESWeb_PFService_EmployeeBalance {
            get {
                return ((string)(this["SESWeb_PFService_EmployeeBalance"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pidevl.bi.com:50000/XISOAPAdapter/MessageServlet?channel=:BS_BI_TARGET_WEB" +
            "PORTAL_D:SOAPSender_PAStatusFromWEBPORTAL&version=3.0&Sender.Service=BS_BI_TARGE" +
            "T_WEBPORTAL_D&Interface=urn%3ATARGET%3AWEBPORTAL%3APAStatus%5EPAStatusFromWEBPOR" +
            "TAL_Out")]
        public string SESWeb_WsvcPASystem_PAStatusFromWEBPORTAL_OutService {
            get {
                return ((string)(this["SESWeb_WsvcPASystem_PAStatusFromWEBPORTAL_OutService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"http://bilpip.bi.com:50000/XISOAPAdapter/MessageServlet?channel=:BS_BI_TARGET_WEBPORTAL_D:SOAPSender_CashVoucherFromWEBPORTAL&version=3.0&Sender.Service=SOAPSender_CashVoucherFromWEBPORTAL+&Interface=urn%3ATARGET%3AWEBPORTAL%3ACashVoucher%5ECashVoucherFromWEBPORTAL_Out")]
        public string DUNPCostingWeb_wsvcSAPPIExpenseReimbursement_CashVoucherFromWEBPORTAL_OutService {
            get {
                return ((string)(this["DUNPCostingWeb_wsvcSAPPIExpenseReimbursement_CashVoucherFromWEBPORTAL_OutService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://brakesindia.versionsystems.com/WebService/EmployeeBalance.asmx")]
        public string DUNPCostingWeb_PFService_EmployeeBalance {
            get {
                return ((string)(this["DUNPCostingWeb_PFService_EmployeeBalance"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pidevl.bi.com:50000/XISOAPAdapter/MessageServlet?channel=:BS_BI_TARGET_WEB" +
            "PORTAL_D:SOAPSender_PAStatusFromWEBPORTAL&version=3.0&Sender.Service=BS_BI_TARGE" +
            "T_WEBPORTAL_D&Interface=urn%3ATARGET%3AWEBPORTAL%3APAStatus%5EPAStatusFromWEBPOR" +
            "TAL_Out")]
        public string DUNPCostingWeb_WsvcPASystem_PAStatusFromWEBPORTAL_OutService {
            get {
                return ((string)(this["DUNPCostingWeb_WsvcPASystem_PAStatusFromWEBPORTAL_OutService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"http://pidsyb.brakesindia.org:50000/XISOAPAdapter/MessageServlet?channel=:BS_BI_TARGET_WEBPORTAL_D:SOAPSender_ServiceSheetFileDetailsFromWEBPORTAL&version=3.0&Sender.Service=BS_BI_TARGET_WEBPORTAL_D&Interface=urn%3ATARGET%3AWEBPORTAL%3AServiceSheetFileDetails%5EServiceSheetFileDetailsFromWEBPORTAL_Out")]
        public string SESWeb_wsvcServiceSheet_ServiceSheetFileDetailsFromWEBPORTAL_OutService {
            get {
                return ((string)(this["SESWeb_wsvcServiceSheet_ServiceSheetFileDetailsFromWEBPORTAL_OutService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"http://pidsyb.brakesindia.org:50000/XISOAPAdapter/MessageServlet?channel=:BS_BI_TARGET_WEBPORTAL_D:SOAPSender_ServiceSheetFileDetailsFromWEBPORTAL&version=3.0&Sender.Service=BS_BI_TARGET_WEBPORTAL_D&Interface=urn%3ATARGET%3AWEBPORTAL%3AServiceSheetFileDetails%5EServiceSheetFileDetailsFromWEBPORTAL_Out")]
        public string SESWeb_wsSES_ServiceSheetFileDetailsFromWEBPORTAL_OutService {
            get {
                return ((string)(this["SESWeb_wsSES_ServiceSheetFileDetailsFromWEBPORTAL_OutService"]));
            }
        }
    }
}
