name: .NET Framework Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: self-hosted  # Use a runner with .NET Framework 4.6.1 support

    env:
      Solution_Name: SES.sln
      Test_Project_Path: SESWeb/SESWeb.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore $env:Solution_Name
        env:
          NUGET_VERSION: 5.x.x  # Adjust to the latest NuGet version

      # Restore the application
      - name: Restore the application
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}

      # Build the solution
      - name: Build the solution
        run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}

      # Execute unit tests (if any)
      - name: Execute unit tests
        run: mstest $env:Test_Project_Path /testcontainer:bin\${{ matrix.configuration }}\$env:Test_Project_Path  # Adjust paths if needed
        env:
          Configuration: ${{ matrix.configuration }}
