name: Build and Deploy .NET Framework 4.6.1 Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      Publish_Output_Path: D:\Deployment\Output

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.3

      - name: Restore NuGet Packages
        run: nuget restore SES.sln

      - name: Build
        run: msbuild /p:Configuration=Release SES.sln /v:diag

      - name: Deploy to Azure App Service
        uses: Azure/webapps-deploy@v2
        with:
          app-name: '<Your-Azure-App-Service-Name>'
          publish-profile: '<Your-Azure-App-Service-Publish-Profile>'
          package: '$(System.DefaultWorkingDirectory)/**/bin/Release/*.*'
        env:
          MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe'  # Path to MSBuild on the runner
          CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.SP_TENANT_ID }}
          SUBSCRIPTION_ID: ${{ secrets.SP_SUBSCRIPTION_ID }}
