name: Build and Deploy .NET Framework 4.6.1 Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET }}
      TENANT_ID: ${{ secrets.SP_TENANT_ID }}
      SUBSCRIPTION_ID: ${{ secrets.SP_SUBSCRIPTION_ID }}
      ACTIONS_AZURE_REST_IGNORE_SSL_ERRORS: true  # Ignore SSL certificate errors

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.3

      - name: Restore NuGet Packages
        run: nuget restore SES.sln

      - name: Build with Publish
        run: msbuild /p:Configuration=Release /p:DeployOnBuild=true /p:PublishDir=SESWeb\bin\app.publish\BrakesDev/wwwroot/SES/ /v:diag

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: SESWeb\bin\app.publish\BrakesDev/wwwroot/SES/
          if-no-files-found: warn

      - name: Verify Build Output
        shell: cmd
        run: dir "SESWeb\bin\app.publish\BrakesDev/wwwroot/SES/"

      - name: Deploy to Azure App Service
        uses: Azure/webapps-deploy@v2
        with:
          publish-profile: |
            <publishData>
              <publishProfile profileName="BrakesDev - Web Deploy" publishMethod="MSDeploy" publishUrl="brakesdev.scm.azurewebsites.net:443/msdeploy.axd?site=BrakesDev" msdeploySite="BrakesDev" userName="$BrakesDev" userPWD="j6bkBcMPAxpZcLpp6rvBo4lhJd0RjdkMv4EaGsamppJmdAe4BHCwrKstHoPd" destinationAppUrl="https://brakesdev.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites">
                <databases />
              </publishProfile>
            </publishData>
          package: SESWeb\bin\app.publish\BrakesDev/wwwroot/SES/
        env:
          MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe'
          CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.SP_TENANT_ID }}
          SUBSCRIPTION_ID: ${{ secrets.SP_SUBSCRIPTION_ID }}
          ACTIONS_AZURE_REST_IGNORE_SSL_ERRORS: true  # Ignore SSL certificate errors
