name: Build and Deploy .NET Framework 4.6.1 Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      Publish_Output_Path: D:\Deployment\Output

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore NuGet Packages
        run: nuget restore SES.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.3

      - name: Run MSBuild
        run: msbuild /p:Configuration=Release SES.sln
