name: Build and Deploy .NET Framework 4.6.1 Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET }}
      TENANT_ID: ${{ secrets.SP_TENANT_ID }}
      SUBSCRIPTION_ID: ${{ secrets.SP_SUBSCRIPTION_ID }}
      ACTIONS_AZURE_REST_IGNORE_SSL_ERRORS: true  # Ignore SSL certificate errors

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.3

      - name: Restore NuGet Packages
        run: nuget restore SES.sln

      - name: Build
        run: msbuild /p:Configuration=Release /p:DeployOnBuild=true /p:PublishDir=SESWeb\bin\app.publish /v:diag

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: SESWeb\bin\app.publish
          if-no-files-found: warn

      - name: Verify Build Output
        shell: cmd
        run: dir "SESWeb\bin\app.publish"

      - name: Deploy to Azure App Service
        id: azure-deploy
        uses: Azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          package: SESWeb\bin\app.publish
        env:
          MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe'
          CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.SP_TENANT_ID }}
          SUBSCRIPTION_ID: ${{ secrets.SP_SUBSCRIPTION_ID }}
          ACTIONS_AZURE_REST_IGNORE_SSL_ERRORS: true  # Ignore SSL certificate errors

  copy-and-deploy:
    runs-on: self-hosted
    needs: build-and-deploy
    steps:
      - name: Get Azure Deployment Path
        shell: powershell
        run: |
          $DEPLOYMENT_PATH = Select-String -Pattern '(?<=destinationAppUrl=")[^"]*' -InputObject "${{ steps.azure-deploy.outputs.publish-profile }}" | ForEach-Object { $_.Matches[0].Value }
          echo "DEPLOYMENT_PATH=$DEPLOYMENT_PATH" >> $env:GITHUB_ENV
      - name: Copy Files from Azure Deployment
        run: |
          mkdir -p brakesdev/SES
          az login --service-principal -u $env:CLIENT_ID -p $env:CLIENT_SECRET --tenant $env:TENANT_ID
          az storage blob download-batch --source $env:DEPLOYMENT_PATH -d brakesdev/SES --pattern "*" --account-name brakesdev
      - name: Deploy to Azure App Service - SES Folder
        uses: Azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          package: brakesdev/SES
        env:
          MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe'
          CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.SP_TENANT_ID }}
          SUBSCRIPTION_ID: ${{ secrets.SP_SUBSCRIPTION_ID }}
          ACTIONS_AZURE_REST_IGNORE_SSL_ERRORS: true  # Ignore SSL certificate errors
